Update monad-logger upper bound
0.3.38 (which I think should have been 0.4?) removed instances that `yesod-core` depended on. Without this, we get:

```
src/Yesod/Core/Class/Handler.hs:79:10: error:
    • Could not deduce (MonadLogger (ListT m))
        arising from the superclasses of an instance declaration
      from the context: MonadHandler m
        bound by the instance declaration
        at src/Yesod/Core/Class/Handler.hs:79:10-49
    • In the instance declaration for ‘MonadHandler (ListT m)’
   |
79 | GO(ListT)
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```