Update yesod-test.cabal
This fixes the following errors that occur when running `cabal check`.

```
The following errors are likely to affect your build negatively:
Error: [git-protocol] Cloning over git:// might lead to an arbitrary
code
execution vulnerability. Furthermore, popular forges like GitHub do not
support it. Use https:// or ssh:// instead.
These warnings may cause trouble when distributing the package:
Warning: [missing-upper-bounds] On library, these packages miss upper
bounds:
- aeson
- attoparsec
- blaze-builder
- blaze-html
- blaze-markup
- bytestring
- case-insensitive
- conduit
- containers
- cookie
- directory
- html-conduit
- http-types
- HUnit
- memory
- mtl
- network
- pretty-show
- process
- text
- time
- transformers
- wai
- wai-extra
- xml-conduit
- xml-types
- yesod-core
Please add them. There is more information at https://pvp.haskell.org/
Error: Hackage would reject this package.
```